spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}/${RDS_DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
server:
  port: 8443
  ssl:
    enabled: false